### PR TITLE
Added react based text utility

### PR DESCRIPTION
**Pull request by MR-DHRUV**
Added a text utility that can
✔ Parse text from HTML
✔ Convert to lowercase, UPPERCASE, and Capitalize
✔ Remove extra spaces
✔ Can tell no of words and characters entered

image

### CODE REVIEW

**Comment by MR-DHRUV** [comment]
This is in refrance to issue no : #1533

**Comment by fineanmol** [comment]
@MR-DHRUV  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by MR-DHRUV** [comment]
@fineanmol please add hactober-accepted label :-)

**Comment by MR-DHRUV** [comment]
@fineanmol Thanks :-)
happy hacking !

**Comment by MR-DHRUV** [comment]
@fineanmol 
your repo has been removed from hactober **PLEASE ADD THIS IN YOUR README AND SAVE SOMEONE'S TIME**

**Pull request merged**
