### PR TITLE
Code for Activity selection problem

### PR DESCRIPTION
**Pull request by piyush-kash**
using Greedy apporoach

# Problem
-On hover Box-Item grows in size now
# Solution
-transform property added to box-item on hover

## Changes proposed in this Pull Request :
-  `1.`transform property added to box-item on hover
-  `2.`on hover color of the contributors name changes to navy
-  `..`

## Other changes
-

### CODE REVIEW

**Comment by fineanmol** [comment]
@piyush-kash  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by piyush-kash** [comment]
done

**Comment by piyush-kash** [comment]
Please reopen PR and merge

**Comment by piyush-kash** [comment]
ur repo is excluded from the fest

**Pull request merged**
