### PR TITLE
Created leetcode-Count_Primes.cpp

### PR DESCRIPTION
**Pull request by raj-hero**
This is the solution to leetcode's Count Primes question using "sieve" algorithm.

### CODE REVIEW

**Comment by raj-hero** [comment]
@fineanmol Will this pull request be marked as hacktoberfest-accepted?

**Comment by fineanmol** [comment]
@raj-hero  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by raj-hero** [comment]
I've already starred the repo. Do add the tag.
Thanks!

**Comment by raj-hero** [comment]
@fineanmol is the repo excluded from hacktoberfest?

**Comment by raj-hero** [comment]
@fineanmol Why isn't the changes made by me visible in the repo?

**Comment by raj-hero** [comment]
@fineanmol  is the repo excluded from hacktoberfest?
Screen Shot 2022-10-02 at 11 45 24 AM

**Pull request merged**
