### PR TITLE
Create Merge-Unsorted-Array.cpp

### PR DESCRIPTION
**Pull request by iam-anish**

### CODE REVIEW

**Comment by fineanmol** [comment]
@iam-anish  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by iam-anish** [comment]
@fineanmol Done 👍

**Comment by iam-anish** [comment]
@fineanmol Why my hacktoberfest profile is showing me "Excluded" in this PR.

**Comment by ItzLevvie** [comment]
This repository has been **_permanently_** excluded from Hacktoberfest 2022. This means that any pull requests (PRs) made to this repository **_will_** not be counted towards your contributions for Hacktoberfest 2022.

Please contribute to **_valuable_** repositories instead of sending pull requests (PRs) to repositories that are there to defeat the whole purpose of Hacktoberfest 2022.

Any repeated, continuous exclusions will automatically ban your account from participating in Hacktoberfest 2022.

**Comment by iam-anish** [comment]
@ItzLevvie my PR is getting "Excluded" can u help me plz? I'm not able to find active repositories

**Pull request merged**
