### PR TITLE
Added Merge Sort Algorithm in Java

### PR DESCRIPTION
**Pull request by LiQuiD-404**
# Problem
Sorting of arrays takes O(n^2)
# Solution
Implemented an efficient sorting algorithm which takes O(NlogN) time.

Worked on this under Hacktoberfest.

### CODE REVIEW

**Comment by fineanmol** [comment]
@LiQuiD-404  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by LiQuiD-404** [comment]
@fineanmol Already done. Please add the tag. Thanks

**Comment by LiQuiD-404** [comment]
image

**Comment by LiQuiD-404** [comment]
image
Why does it say this? @fineanmol

**Pull request merged**
