### PR TITLE
session concept added

### PR DESCRIPTION
**Pull request by sayon-som**
# Problem
-On hover Box-Item grows in size now
# Solution
-transform property added to box-item on hover

## Changes proposed in this Pull Request :
-  `1.`transform property added to box-item on hover
-  `2.`on hover color of the contributors name changes to navy
-  `..`

## Other changes
-

### CODE REVIEW

**Comment by fineanmol** [comment]
@sayon-som  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by sayon-som** [comment]
added

**Comment by sayon-som** [comment]
its showing your repo has been excluded .

**Comment by fineanmol** [comment]
> its showing your repo has been excluded .

you can contribute here : https://github.com/fineanmol/hacktoberfest
this repo is included

**Pull request merged**
